import { useMemo } from "react";
import { useAppContext } from "@/app/AppContext";
import { buildProvidersWorkspaceProps } from "@/features/providers/model/providersWorkspaceProps";
import { buildProvidersWorkspaceState } from "@/features/providers/model/providersWorkspaceModel";

export function useProvidersWorkspaceProps() {
  const context = useAppContext();
  const {
    messages,
    visibleProviders: providers,
    visibleProviderSummary: providerSummary,
    providerMatrixLoading,
    visibleProviderTabs: providerTabs,
    visibleSlowProviderIds: slowProviderIds,
    slowProviderThresholdMs,
    setSlowProviderThresholdMs,
    providerView,
    setProviderView,
    providerDataDepth,
    setProviderDataDepth,
    visibleProviderSessionRows: providerSessionRows,
    allVisibleProviderSessionRows: allProviderSessionRows,
    allProviderSessionProviders,
    visibleProviderSessionSummary: providerSessionSummary,
    providerSessionsLimit,
    providerRowsSampled,
    visibleDataSourceRows: dataSourceRows,
    dataSourcesLoading,
    providerSessionsLoading,
    selectedProviderFiles,
    setSelectedProviderFiles,
    visibleAllProviderRowsSelected: allProviderRowsSelected,
    toggleSelectAllProviderRows,
    selectedProviderLabel,
    selectedProviderFilePaths,
    providerActionProvider,
    canRunProviderAction,
    busy,
    providerSessionActionPending,
    recoveryBackupExportPending,
    groupedBackupProgress,
    providerDeleteBackupEnabled,
    setProviderDeleteBackupEnabled,
    backupRoot,
    setBackupRoot,
    exportRoot,
    setExportRoot,
    latestExportArchivePath,
    runProviderAction,
    runProviderConfirmedAction,
    runPreparedProviderAction,
    runGroupedProviderBackup,
    runGroupedProviderBackupExport,
    runProviderHardDelete,
    providerActionData,
    providerActionSelection,
    runRecoveryBackupExport,
    recoveryBackupExportData,
    recoveryData,
    visibleParserReports: parserReports,
    allVisibleParserReports: allParserReports,
    parserLoading,
    visibleParserSummary: parserSummary,
    selectedSessionPath,
    setSelectedSessionPath,
    providersRefreshing,
    providersLastRefreshAt,
    providerFetchMetrics,
    refreshProvidersData,
    selectedSession,
    emptySessionScopeLabel,
    emptySessionNextTitle,
    emptySessionNextPath,
    sessionTranscriptData,
    sessionTranscriptLoading,
    sessionTranscriptLimit,
    setSessionTranscriptLimit,
    canRunSelectedSessionAction,
    runSingleProviderAction,
    runSingleProviderHardDelete,
    providersDiagnosticsOpen,
    setProvidersDiagnosticsOpen,
    handleDiagnosticsIntent,
    showRouting,
    executionGraphData,
    executionGraphLoading,
    visibleProviderIds,
    providerProbeFilterIntent,
    setProviderProbeFilterIntent,
  } = context;

  const workspaceState = useMemo(
    () =>
      buildProvidersWorkspaceState({
        messages,
        providerSessionRows,
        selectedProviderFiles,
        emptySessionNextTitle,
        emptySessionNextPath,
        selectedSession,
        providerActionData,
        providerActionSelection,
      }),
    [
      messages,
      providerSessionRows,
      selectedProviderFiles,
      emptySessionNextTitle,
      emptySessionNextPath,
      selectedSession,
      providerActionData,
      providerActionSelection,
    ],
  );

  const workspaceProps = buildProvidersWorkspaceProps({
    messages,
    providers,
    providerSummary,
    providerMatrixLoading,
    providerTabs,
    slowProviderIds,
    slowProviderThresholdMs,
    setSlowProviderThresholdMs,
    providerView,
    setProviderView,
    providerDataDepth,
    setProviderDataDepth,
    providerSessionRows,
    allProviderSessionRows,
    allProviderSessionProviders,
    providerSessionSummary,
    providerSessionsLimit,
    providerRowsSampled,
    dataSourceRows,
    dataSourcesLoading,
    providerSessionsLoading,
    selectedProviderFiles,
    setSelectedProviderFiles,
    allProviderRowsSelected,
    toggleSelectAllProviderRows,
    selectedProviderLabel,
    selectedProviderFilePaths,
    providerActionProvider,
    canRunProviderAction,
    busy,
    providerSessionActionPending,
    recoveryBackupExportPending,
    groupedBackupProgress,
    providerDeleteBackupEnabled,
    setProviderDeleteBackupEnabled,
    backupRoot,
    setBackupRoot,
    exportRoot,
    setExportRoot,
    latestExportArchivePath,
    runProviderAction,
    runProviderConfirmedAction,
    runPreparedProviderAction,
    runGroupedProviderBackup,
    runGroupedProviderBackupExport,
    runProviderHardDelete,
    providerActionData,
    providerActionSelection,
    runRecoveryBackupExport,
    recoveryBackupExportData,
    recoveryData,
    parserReports,
    allParserReports,
    parserLoading,
    parserSummary,
    selectedSessionPath,
    setSelectedSessionPath,
    providersRefreshing,
    providersLastRefreshAt,
    providerFetchMetrics,
    refreshProvidersData,
    providerProbeFilterIntent,
    setProviderProbeFilterIntent,
    selectedSession,
    selectedSessionCount: workspaceState.selectedSessionCount,
    selectedSessionActionResult: workspaceState.selectedSessionActionResult,
    emptySessionScopeLabel,
    emptyNextSessions: workspaceState.emptyNextSessions,
    sessionTranscriptData,
    sessionTranscriptLoading,
    sessionTranscriptLimit,
    setSessionTranscriptLimit,
    canRunSelectedSessionAction,
    runSingleProviderAction,
    runSingleProviderHardDelete,
    executionGraphData,
    executionGraphLoading,
    visibleProviderIds,
    sessionDetailKey: workspaceState.sessionDetailKey,
  });

  const onToggleDiagnostics = (nextOpen: boolean) => {
    setProvidersDiagnosticsOpen(nextOpen);
    if (nextOpen) handleDiagnosticsIntent();
  };

  return {
    messages,
    providersDiagnosticsOpen,
    showRouting,
    onToggleDiagnostics,
    ...workspaceProps,
  };
}
