import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const tokensStyles = readFileSync(new URL("../styles/tokens.css", import.meta.url), "utf8");

describe("tokens surface migration", () => {
  it("uses named blur tokens for light workbench surfaces", () => {
    expect(tokensStyles).toMatch(/--blur-light-panel:\s*14px;/);
    expect(tokensStyles).toMatch(/:root\[data-theme="light"\] \.provider-archive-stage,[\s\S]*?\.routing-workbench-panel\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-light-panel\)\);/s);
  });

  it("defines semantic search surface and text tokens", () => {
    expect(tokensStyles).toMatch(/--surface-search-command-shell:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 74%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-breadcrumb-active:\s*color-mix\(in srgb, var\(--accent-dim\) 78%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-command-bar:\s*color-mix\(in srgb, var\(--surface-card-bg\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--text-search-muted:\s*color-mix\(in srgb, var\(--muted\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-command-kbd:\s*color-mix\(in srgb, var\(--surface-card-bg\) 68%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-guide-card:\s*color-mix\(in srgb, var\(--panel\) 92%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-result-stage:\s*color-mix\(in srgb, var\(--surface-card-bg\) 82%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-result-stage-hover:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 88%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-inline-strip:\s*color-mix\(in srgb, var\(--surface-card-bg\) 68%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-inline-strip-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-live-dot:\s*color-mix\(in srgb, var\(--accent\) 84%, white\);/);
    expect(tokensStyles).toMatch(/--shadow-search-live-dot:\s*0 0 0 6px color-mix\(in srgb, var\(--accent\) 14%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-loading-row:\s*color-mix\(in srgb, var\(--bg-elev\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-divider-soft:\s*color-mix\(in srgb, var\(--line-soft\) 85%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-result-hover-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 86%, var\(--accent\) 14%\);/);
    expect(tokensStyles).toMatch(/--surface-search-result-hover:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 90%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-inline-pill:\s*color-mix\(in srgb, var\(--surface-pill-bg\) 86%, transparent\);/);
    expect(tokensStyles).toMatch(/--text-search-inline-hover:\s*color-mix\(in srgb, var\(--text\) 92%, #2f4358\);/);
    expect(tokensStyles).toMatch(/--text-search-link-soft:\s*color-mix\(in srgb, var\(--accent\) 76%, white\);/);
    expect(tokensStyles).toMatch(/--text-search-link-strong:\s*color-mix\(in srgb, var\(--accent\) 92%, white\);/);
    expect(tokensStyles).toMatch(/--surface-search-result-active-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 80%, var\(--accent\) 20%\);/);
    expect(tokensStyles).toMatch(/--shadow-search-result-active-glow:\s*0 0 18px color-mix\(in srgb, var\(--accent\) 12%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-preview-empty-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 92%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-search-preview-empty-bg:\s*color-mix\(in srgb, var\(--surface-card-bg\) 54%, transparent\);/);
  });

  it("defines semantic component surface tokens", () => {
    expect(tokensStyles).toMatch(/--surface-kpi-info:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--info\) 10%, transparent\), transparent 60%\),\s*var\(--surface-card-bg-subtle\);/);
    expect(tokensStyles).toMatch(/--surface-kpi-warn:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--warn\) 10%, transparent\), transparent 60%\),\s*var\(--surface-card-bg-subtle\);/);
    expect(tokensStyles).toMatch(/--surface-kpi-success:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--success\) 10%, transparent\), transparent 60%\),\s*var\(--surface-card-bg-subtle\);/);
    expect(tokensStyles).toMatch(/--surface-form-field-border:\s*color-mix\(in srgb, var\(--line\) 70%, var\(--accent\) 18%\);/);
    expect(tokensStyles).toMatch(/--surface-form-field-bg:\s*var\(--bg-elev\);/);
    expect(tokensStyles).toMatch(/--btn-base-bg:\s*rgba\(56, 66, 76, 0\.98\);/);
    expect(tokensStyles).toMatch(/--btn-base-hover-bg:\s*rgba\(70, 82, 93, 1\);/);
    expect(tokensStyles).toMatch(/--btn-accent-bg:\s*rgba\(88, 113, 136, 0\.98\);/);
    expect(tokensStyles).toMatch(/--btn-accent-hover-bg:\s*rgba\(103, 129, 153, 1\);/);
    expect(tokensStyles).toMatch(/--btn-outline-text:\s*var\(--accent-strong\);/);
    expect(tokensStyles).toMatch(/--btn-danger-bg:\s*rgba\(98, 35, 35, 0\.94\);/);
    expect(tokensStyles).toMatch(/--btn-danger-hover-bg:\s*rgba\(122, 43, 43, 0\.98\);/);
    expect(tokensStyles).toMatch(/--btn-danger-text:\s*#ffe4e6;/);
    expect(tokensStyles).toMatch(/--surface-btn-outline:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 36%, var\(--accent-dim\)\);/);
    expect(tokensStyles).toMatch(/--surface-btn-outline-hover:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 18%, var\(--accent-dim\)\);/);
    expect(tokensStyles).toMatch(/--surface-btn-outline-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 68%, var\(--accent\) 32%\);/);
    expect(tokensStyles).toMatch(/--surface-btn-outline-border-hover:\s*color-mix\(in srgb, var\(--surface-card-border\) 44%, var\(--accent\) 56%\);/);
    expect(tokensStyles).toMatch(/--surface-panel-frosted:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--panel-glass\) 74%, var\(--glass-high\)\), color-mix\(in srgb, var\(--panel\) 78%, transparent\)\),\s*color-mix\(in srgb, var\(--panel-glass\) 74%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-border:\s*color-mix\(in srgb, var\(--accent\) 16%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-panel-sheen:\s*color-mix\(in srgb, white 8%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-status-preview-hover-border:\s*color-mix\(in srgb, var\(--info\) 32%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-provider-slow-badge:\s*color-mix\(in srgb, var\(--warn-dim\) 80%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-provider-slow-row:\s*color-mix\(in srgb, var\(--warn-dim\) 55%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-provider-slow-row-hover:\s*color-mix\(in srgb, var\(--warn-dim\) 70%, var\(--hover\)\);/);
    expect(tokensStyles).toMatch(/--surface-active-row-bg:\s*color-mix\(in srgb, var\(--accent\) 14%, var\(--bg-elev\)\);/);
    expect(tokensStyles).toMatch(/:root\[data-theme="light"\]\s*{[\s\S]*?--btn-outline-text:\s*var\(--surface-active-text\);/);
    expect(tokensStyles).toMatch(/:root\[data-theme="light"\]\s*{[\s\S]*?--surface-btn-outline:\s*var\(--btn-accent-bg\);/);
    expect(tokensStyles).toMatch(/:root\[data-theme="light"\]\s*{[\s\S]*?--surface-btn-outline-hover:\s*var\(--btn-accent-hover-bg\);/);
  });

  it("defines semantic routing surface and state tokens", () => {
    expect(tokensStyles).toMatch(/--surface-impact-kv:\s*color-mix\(in srgb, var\(--surface-card-bg\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle:\s*color-mix\(in srgb, var\(--bg-elev\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle-strong:\s*color-mix\(in srgb, var\(--bg-elev\) 76%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle:\s*color-mix\(in srgb, var\(--panel\) 90%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle-strong:\s*color-mix\(in srgb, var\(--panel\) 88%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-track-muted:\s*color-mix\(in srgb, var\(--bg\) 65%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--surface-track-muted-strong:\s*color-mix\(in srgb, var\(--bg\) 70%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-info-border-soft:\s*color-mix\(in srgb, var\(--info\) 40%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-success-border-soft:\s*color-mix\(in srgb, var\(--success\) 34%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-soft:\s*color-mix\(in srgb, var\(--warn\) 38%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-accent-border-soft:\s*color-mix\(in srgb, var\(--accent\) 38%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-success-border-soft-strong:\s*color-mix\(in srgb, var\(--success\) 46%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-danger-border-soft:\s*color-mix\(in srgb, var\(--danger\) 32%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-success-border:\s*color-mix\(in srgb, var\(--success\) 35%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-success-bg:\s*color-mix\(in srgb, var\(--success-dim\) 70%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-success-bg-soft:\s*color-mix\(in srgb, var\(--success-dim\) 68%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-success-bg-strong:\s*color-mix\(in srgb, var\(--success-dim\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-warn-border:\s*color-mix\(in srgb, var\(--warn\) 35%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-muted:\s*color-mix\(in srgb, var\(--warn\) 30%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-medium:\s*color-mix\(in srgb, var\(--warn\) 40%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-soft-strong:\s*color-mix\(in srgb, var\(--warn\) 38%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-strong:\s*color-mix\(in srgb, var\(--warn\) 42%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-bg:\s*color-mix\(in srgb, var\(--warn-dim\) 70%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-warn-bg-soft:\s*color-mix\(in srgb, var\(--warn-dim\) 68%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-warn-bg-strong:\s*color-mix\(in srgb, var\(--warn-dim\) 80%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-info-border:\s*color-mix\(in srgb, var\(--info\) 35%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-info-border-weak:\s*color-mix\(in srgb, var\(--info\) 34%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-info-bg:\s*color-mix\(in srgb, var\(--info-dim\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-info-bg-strong:\s*color-mix\(in srgb, var\(--info-dim\) 78%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-danger-border:\s*color-mix\(in srgb, #ef4444 40%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-success-fill-gradient:\s*linear-gradient\(90deg, color-mix\(in srgb, var\(--success\) 70%, #a7f3d0\), var\(--success\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-fill-gradient:\s*linear-gradient\(90deg, color-mix\(in srgb, var\(--warn\) 60%, #fde68a\), var\(--warn\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-fill-gradient-strong:\s*linear-gradient\(90deg, color-mix\(in srgb, var\(--warn\) 55%, #fde68a\), var\(--warn\)\);/);
    expect(tokensStyles).toMatch(/--state-info-fill-gradient:\s*linear-gradient\(90deg, color-mix\(in srgb, var\(--info\) 55%, #93c5fd\), var\(--info\)\);/);
    expect(tokensStyles).toMatch(/--state-success-fill-gradient-soft:\s*linear-gradient\(90deg, color-mix\(in srgb, var\(--success\) 45%, #86efac\), var\(--success\)\);/);
  });

  it("defines semantic provider surface tokens", () => {
    expect(tokensStyles).toMatch(/--surface-stage-border-subtle:\s*color-mix\(in srgb, var\(--surface-stage-border\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-stage-border-soft:\s*color-mix\(in srgb, var\(--surface-stage-border\) 78%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-text-muted-dot:\s*color-mix\(in srgb, var\(--text-secondary\) 58%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-workspace-active-border:\s*color-mix\(in srgb, var\(--accent\) 36%, var\(--surface-card-border\)\);/);
    expect(tokensStyles).toMatch(/--surface-workspace-active-bg:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 82%, var\(--accent-dim\)\);/);
    expect(tokensStyles).toMatch(/--surface-divider-subtle:\s*color-mix\(in srgb, var\(--surface-card-border\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-divider-strong:\s*color-mix\(in srgb, var\(--surface-card-border\) 76%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-divider-muted:\s*color-mix\(in srgb, var\(--surface-card-border\) 62%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-divider-faint:\s*color-mix\(in srgb, var\(--surface-card-border\) 58%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-card-accent-border-strong:\s*color-mix\(in srgb, var\(--accent\) 30%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-card-accent-border-muted:\s*color-mix\(in srgb, var\(--accent\) 26%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-card-accent-border:\s*color-mix\(in srgb, var\(--accent\) 32%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle-soft:\s*color-mix\(in srgb, var\(--panel\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle-mid:\s*color-mix\(in srgb, var\(--panel\) 86%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle-balanced:\s*color-mix\(in srgb, var\(--panel\) 80%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-stage-subtle-strong:\s*color-mix\(in srgb, var\(--surface-stage-bg\) 80%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-stage-soft:\s*color-mix\(in srgb, var\(--surface-stage-bg\) 78%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle-soft:\s*color-mix\(in srgb, var\(--bg-elev\) 68%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle-mid:\s*color-mix\(in srgb, var\(--bg-elev\) 80%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-success-border-soft-base:\s*color-mix\(in srgb, var\(--success\) 35%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-success-bg-muted:\s*color-mix\(in srgb, var\(--success-dim\) 65%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-warn-border-soft-base:\s*color-mix\(in srgb, var\(--warn\) 35%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--state-warn-bg-balanced:\s*color-mix\(in srgb, var\(--warn-dim\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--state-muted-border:\s*color-mix\(in srgb, var\(--muted\) 45%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--state-muted-border-soft:\s*color-mix\(in srgb, var\(--muted\) 45%, var\(--line-soft\)\);/);
    expect(tokensStyles).toMatch(/--surface-session-table-head:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 88%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-session-row-alt:\s*color-mix\(in srgb, var\(--surface-card-bg\) 44%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-session-row-hover:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 64%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-danger-panel-border:\s*color-mix\(in srgb, var\(--danger\) 32%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-danger-panel-bg:\s*color-mix\(in srgb, var\(--danger\) 7%, var\(--panel\)\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle-max:\s*color-mix\(in srgb, var\(--bg-elev\) 90%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-elevated-subtle-alt:\s*color-mix\(in srgb, var\(--bg-elev\) 74%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-tab-warn:\s*color-mix\(in srgb, var\(--tab-bg\) 84%, var\(--warn-dim\)\);/);
    expect(tokensStyles).toMatch(/--surface-table-wrap:\s*color-mix\(in srgb, var\(--surface-card-bg\) 74%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-table-header:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--surface-card-bg-strong\) 62%, transparent\), color-mix\(in srgb, var\(--surface-card-bg\) 42%, transparent\)\);/);
    expect(tokensStyles).toMatch(/--surface-table-toolbar:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 58%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-table-head:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 90%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-table-row-hover:\s*color-mix\(in srgb, var\(--surface-card-bg\) 62%, var\(--hover\)\);/);
    expect(tokensStyles).toMatch(/--surface-table-row-alt:\s*color-mix\(in srgb, var\(--surface-card-bg\) 24%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-table-row-hover-strong:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 66%, var\(--hover\)\);/);
    expect(tokensStyles).toMatch(/--surface-ai-hub-card:\s*linear-gradient\(160deg, color-mix\(in srgb, var\(--bg-elev\) 86%, rgba\(59, 130, 246, 0.08\)\), transparent 72%\),\s*color-mix\(in srgb, var\(--bg-elev\) 82%, transparent\);/);
  });

  it("defines semantic session detail and threads tokens", () => {
    expect(tokensStyles).toMatch(/--surface-review-panel-header:\s*linear-gradient\(180deg,\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 74%, transparent\),\s*color-mix\(in srgb, var\(--surface-stage-bg\) 52%, transparent\)\s*\);/);
    expect(tokensStyles).toMatch(/--surface-review-card-active-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 88%, var\(--accent\) 12%\);/);
    expect(tokensStyles).toMatch(/--surface-review-card-active-bg:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 88%, var\(--accent-dim\)\);/);
    expect(tokensStyles).toMatch(/--shadow-review-card-active:\s*0 0 0 1px color-mix\(in srgb, var\(--surface-card-border\) 72%, var\(--accent\) 16%\);/);
    expect(tokensStyles).toMatch(/--surface-detail-section-open-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 86%, var\(--text\) 14%\);/);
    expect(tokensStyles).toMatch(/--surface-detail-divider:\s*color-mix\(in srgb, var\(--surface-card-border\) 82%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-detail-chat-log:\s*color-mix\(in srgb, var\(--surface-card-bg\) 78%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-detail-action-bar:\s*color-mix\(in srgb, var\(--surface-nav-bg\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-detail-empty-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 74%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-detail-action-bar-ghost:\s*color-mix\(in srgb, var\(--surface-nav-bg\) 66%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-panel-header:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--panel-glass\) 64%, var\(--glass-high\)\), color-mix\(in srgb, var\(--panel\) 88%, transparent\)\),\s*var\(--gradient-accent-subtle\);/);
    expect(tokensStyles).toMatch(/--surface-cleanup-header:\s*linear-gradient\(180deg, color-mix\(in srgb, var\(--surface-card-bg-strong\) 62%, transparent\), color-mix\(in srgb, var\(--surface-stage-bg\) 42%, transparent\)\);/);
    expect(tokensStyles).toMatch(/--surface-thread-status-card:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 76%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-thread-status-ready-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 90%, var\(--accent\) 10%\);/);
    expect(tokensStyles).toMatch(/--surface-thread-status-ready-bg:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 88%, var\(--accent-dim\)\);/);
    expect(tokensStyles).toMatch(/--surface-thread-status-accent-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 84%, var\(--accent\) 16%\);/);
    expect(tokensStyles).toMatch(/--shadow-thread-status-accent:\s*0 18px 32px -28px color-mix\(in srgb, var\(--accent\) 42%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-provider-result-export:\s*color-mix\(in srgb, var\(--accent\) 12%, var\(--panel\)\);/);
    expect(tokensStyles).toMatch(/--surface-provider-result-code:\s*color-mix\(in srgb, var\(--bg\) 88%, transparent\);/);
  });

  it("defines semantic overview, setup, layout, and chat tokens", () => {
    expect(tokensStyles).toMatch(/--text-body-base:\s*0\.9375rem;/);
    expect(tokensStyles).toMatch(/--text-body-compact:\s*0\.875rem;/);
    expect(tokensStyles).toMatch(/--surface-transcript-summary-strip:\s*color-mix\(in srgb, var\(--bg-elev\) 44%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-chat-action-bar:\s*color-mix\(in srgb, var\(--panel\) 88%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-setup-stage-pill-border:\s*color-mix\(in srgb, var\(--surface-pill-border\) 90%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-setup-complete-compact-border:\s*color-mix\(in srgb, var\(--accent\) 26%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-setup-complete-compact-bg:\s*linear-gradient\(135deg, color-mix\(in srgb, var\(--panel\) 84%, rgba\(99, 102, 241, 0.08\)\), transparent 72%\),\s*color-mix\(in srgb, var\(--panel\) 92%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-setup-active-border:\s*color-mix\(in srgb, var\(--accent\) 55%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-setup-step-done-border:\s*color-mix\(in srgb, var\(--success\) 30%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-setup-choice-selected-bg:\s*color-mix\(in srgb, var\(--accent\) 16%, var\(--panel\)\);/);
    expect(tokensStyles).toMatch(/--text-top-search-placeholder:\s*color-mix\(in srgb, var\(--muted\) 86%, transparent\);/);
    expect(tokensStyles).toMatch(/--text-top-surface-btn:\s*color-mix\(in srgb, var\(--text\) 72%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-active-bg:\s*#181c21;/);
    expect(tokensStyles).toMatch(/--surface-active-text:\s*#f3f6f8;/);
    expect(tokensStyles).toMatch(/--surface-active-border:\s*rgba\(230, 236, 240, 0\.18\);/);
    expect(tokensStyles).toMatch(/--surface-active-shadow:\s*0 0 0 1px rgba\(230, 236, 240, 0\.06\), 0 18px 34px rgba\(0, 0, 0, 0\.42\);/);
    expect(tokensStyles).toMatch(/--surface-provider-select-border:\s*color-mix\(in srgb, var\(--line\) 68%, var\(--accent\) 20%\);/);
    expect(tokensStyles).toMatch(/--surface-provider-select-bg:\s*var\(--bg-elev\);/);
    expect(tokensStyles).toMatch(/--surface-provider-select-sheen:\s*inset 0 1px 0 color-mix\(in srgb, white 7%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-window-dot-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 84%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-window-dot-bg:\s*color-mix\(in srgb, var\(--muted\) 26%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-window-dot-muted:\s*color-mix\(in srgb, var\(--surface-card-bg-strong\) 60%, var\(--muted\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-card-action-quiet-border:\s*color-mix\(in srgb, var\(--surface-pill-border\) 58%, transparent\);/);
    expect(tokensStyles).toMatch(/--text-overview-side-head:\s*color-mix\(in srgb, var\(--text\) 82%, transparent\);/);
    expect(tokensStyles).toMatch(/--text-overview-side-icon:\s*color-mix\(in srgb, var\(--accent\) 60%, var\(--muted\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-history-item-bg:\s*color-mix\(in srgb, var\(--surface-card-bg\) 22%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-history-item-border:\s*color-mix\(in srgb, var\(--surface-card-border\) 42%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-history-item-hover-bg:\s*color-mix\(in srgb, var\(--surface-card-bg\) 76%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-muted-dot:\s*color-mix\(in srgb, var\(--muted\) 42%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-demo-border:\s*color-mix\(in srgb, var\(--accent\) 28%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-demo-bg:\s*linear-gradient\(180deg, rgba\(255,255,255,0.03\), transparent\),\s*color-mix\(in srgb, var\(--panel\) 90%, rgba\(99, 102, 241, 0.08\)\);/);
    expect(tokensStyles).toMatch(/--shadow-overview-demo-step:\s*0 0 0 4px color-mix\(in srgb, var\(--accent\) 10%, transparent\);/);
    expect(tokensStyles).toMatch(/--surface-overview-kick-border:\s*color-mix\(in srgb, var\(--accent\) 30%, var\(--line\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-kick-bg:\s*linear-gradient\(180deg, rgba\(255,255,255,0.03\), transparent\),\s*color-mix\(in srgb, var\(--panel\) 88%, rgba\(99, 102, 241, 0.10\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-secondary-panel:\s*color-mix\(in srgb, var\(--panel\) 92%, rgba\(255, 255, 255, 0.42\)\);/);
    expect(tokensStyles).toMatch(/--surface-overview-secondary-close:\s*color-mix\(in srgb, var\(--panel\) 88%, rgba\(255, 255, 255, 0.68\)\);/);
    expect(tokensStyles).toMatch(/--surface-panel-subtle-max:\s*color-mix\(in srgb, var\(--panel\) 92%, transparent\);/);
  });
});
