import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const providerStyles = readFileSync(new URL("./providers.css", import.meta.url), "utf8");

describe("providers token migration", () => {
  it("uses blur tokens for stage-level shells", () => {
    expect(providerStyles).toMatch(/\.provider-archive-stage\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-lg\)\);/s);
    expect(providerStyles).toMatch(/\.provider-advanced-shell\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-md\)\);/s);
    expect(providerStyles).toMatch(/\.provider-session-stage\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-lg\)\);/s);
    expect(providerStyles).toMatch(/th\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-sm\)\);/s);
    expect(providerStyles).toMatch(/\.provider-routing-tools-row\s*{[^}]*background:\s*var\(--surface-stage-subtle\);[^}]*backdrop-filter:\s*blur\(var\(--blur-md\)\);/s);
    expect(providerStyles).toMatch(/\.provider-archive-stage\s*{[^}]*background:\s*var\(--surface-stage-subtle\);/s);
    expect(providerStyles).toMatch(/\.ai-provider-card\s*{[^}]*background:\s*var\(--surface-card-bg-subtle\);/s);
    expect(providerStyles).toMatch(/\.ai-provider-card\.is-optional\s*{[^}]*background:\s*var\(--surface-card-bg-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-chip-disclosure,\s*\.panel-disclosure\s*{[^}]*background:\s*var\(--surface-card-bg-subtle\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel \.sub-toolbar\s*{[^}]*backdrop-filter:\s*blur\(var\(--blur-sm\)\) saturate\(120%\);/s);
  });

  it("uses typography tokens for shared provider labels", () => {
    expect(providerStyles).toMatch(/\.provider-routing-tools-trigger\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.ai-section-head strong\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.ai-section-head span\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.ai-provider-metrics\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-archive-stage > header span\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-archive-stage > header h2\s*{[^}]*font-size:\s*var\(--text-lg\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-copy strong\s*{[^}]*font-size:\s*var\(--text-lg\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-copy p\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-summary-cell span\s*{[^}]*font-size:\s*var\(--text-2xs\);/s);
    expect(providerStyles).toMatch(/\.ai-management-copy strong\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.ai-management-copy p\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-recent-item \.sub-hint\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-grid-intro-copy p\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-advanced-shell summary\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-advanced-shell \.panel-summary-subcopy\s*{[^}]*font-size:\s*var\(--text-2xs\);/s);
    expect(providerStyles).toMatch(/\.session-routing-disclosure-state\s*{[^}]*font-size:\s*var\(--text-2xs\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table \.mono-sub\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.capability-chip\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-tab-title\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel \.status-pill\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/th\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-recent-item strong\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-summary-cell strong\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-chip-disclosure summary,\s*\.panel-disclosure summary\s*{[^}]*font-size:\s*var\(--text-base\);/s);
  });

  it("uses typography tokens for provider workspace, session tables, and status copy", () => {
    expect(providerStyles).toMatch(/\.provider-workspace-actions-head strong\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-backup-meta\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-selection-preview strong,\s*\.provider-inline-result strong\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-grid-intro-copy strong\s*{[^}]*font-size:\s*var\(--text-lg\);/s);
    expect(providerStyles).toMatch(/\.session-routing-disclosure-copy strong\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.session-routing-disclosure-copy span\s*{[^}]*font-size:\s*var\(--text-2xs\);/s);
    expect(providerStyles).toMatch(/\.ai-hub-metrics span\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.ai-focus-metric span\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.ai-focus-metric strong\s*{[^}]*font-size:\s*var\(--text-lg\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table thead th\s*{[^}]*font-size:\s*var\(--text-xs\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table \.title-main\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table tbody td:not\(\.title-col\)\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.session-detail-empty-copy strong\s*{[^}]*font-size:\s*var\(--text-lg\);/s);
    expect(providerStyles).toMatch(/\.danger-zone-head strong\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.status-pill\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.status-pill-action\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-slow-badge\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.inline-link-btn\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.mono-sub\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.notes-col\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-roots > summary\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.ai-pillar strong\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.ai-pillar p\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.hotspot-meta\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node-label\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node-state\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-arrow\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-config h3\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-config li\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.provider-tab-meta\s*{[^}]*font-size:\s*var\(--text-base\);/s);
    expect(providerStyles).toMatch(/\.sub-toolbar summary\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel > header h2\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel > header span\s*{[^}]*font-size:\s*var\(--text-sm\);/s);
    expect(providerStyles).toMatch(/th,\s*td\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel \.title-main\s*{[^}]*font-size:\s*var\(--text-md\);/s);
    expect(providerStyles).toMatch(/\.data-source-meta\s*{[^}]*font-size:\s*var\(--text-base\);/s);
  });

  it("uses semantic surface tokens for shared provider cards and pills", () => {
    expect(providerStyles).toMatch(/\.provider-routing-tools-row\s*{[^}]*border:\s*1px solid var\(--surface-stage-border-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-routing-tools-main::before\s*{[^}]*background:\s*var\(--surface-text-muted-dot\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-recent-item\.is-active\s*{[^}]*border-color:\s*var\(--surface-workspace-active-border\);[^}]*background:\s*var\(--surface-workspace-active-bg\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-primary,\s*\.provider-workspace-actions\s*{[^}]*background:\s*var\(--surface-card-bg-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-actions\s*{[^}]*background:\s*var\(--surface-card-strong-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-workspace-recent-item\s*{[^}]*background:\s*var\(--surface-card-bg-ghost\);/s);
    expect(providerStyles).toMatch(/\.provider-summary-cell\s*{[^}]*background:\s*var\(--surface-card-bg-ghost\);/s);
    expect(providerStyles).toMatch(/\.provider-selection-preview,\s*\.provider-inline-result\s*{[^}]*background:\s*var\(--surface-card-bg-ghost\);/s);
    expect(providerStyles).toMatch(/\.provider-grid-intro\s*{[^}]*border-bottom:\s*1px solid var\(--surface-divider-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-result-card-backup\s*{[^}]*border-color:\s*var\(--surface-card-accent-border-strong\);[^}]*var\(--surface-panel-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-result-card-selected\s*{[^}]*border-color:\s*var\(--surface-card-accent-border-muted\);[^}]*var\(--surface-panel-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-action-toolbar-emphasis\s*{[^}]*border:\s*1px solid var\(--surface-card-accent-border\);[^}]*var\(--surface-panel-subtle-strong\);/s);
    expect(providerStyles).toMatch(/\.provider-chip\s*{[^}]*background:\s*var\(--surface-pill-ghost\);/s);
    expect(providerStyles).toMatch(/\.provider-chip\.is-active\s*{[^}]*border-color:\s*var\(--surface-active-chip-border\);[^}]*background:\s*var\(--surface-active-chip-bg\);/s);
    expect(providerStyles).toMatch(/\.session-routing-disclosure summary\s*{[^}]*background:\s*var\(--surface-stage-subtle\);/s);
    expect(providerStyles).toMatch(/\.session-routing-disclosure summary\s*{[^}]*border:\s*1px solid var\(--surface-stage-border-soft\);/s);
    expect(providerStyles).toMatch(/\.inline-tools-disclosure\s*{[^}]*background:\s*var\(--surface-panel-subtle-soft\)\s*!important;/s);
    expect(providerStyles).toMatch(/\.ai-hub-card\s*{[^}]*background:\s*var\(--surface-ai-hub-card\);/s);
    expect(providerStyles).toMatch(/\.ai-hub-card\.is-warning\s*{[^}]*border-color:\s*var\(--state-warn-border\);/s);
    expect(providerStyles).toMatch(/\.ai-hub-card\.is-optional\s*{[^}]*background:\s*var\(--surface-panel-subtle-balanced\);/s);
    expect(providerStyles).toMatch(/\.ai-focus-metric\s*{[^}]*background:\s*var\(--surface-panel-subtle-soft\);/s);
    expect(providerStyles).toMatch(/\.ai-pillar\s*{[^}]*background:\s*var\(--surface-panel-subtle-mid\);/s);
    expect(providerStyles).toMatch(/\.provider-session-stage\s*{[^}]*background:\s*var\(--surface-stage-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-table-wrap\s*{[^}]*border-top:\s*1px solid var\(--surface-divider-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table thead th\s*{[^}]*background:\s*var\(--surface-session-table-head\);[^}]*border-bottom:\s*1px solid var\(--surface-border-subtle\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table tbody tr:nth-child\(even\) td\s*{[^}]*background:\s*var\(--surface-session-row-alt\);/s);
    expect(providerStyles).toMatch(/\.provider-session-table tbody tr:hover td\s*{[^}]*background:\s*var\(--surface-session-row-hover\);/s);
    expect(providerStyles).toMatch(/\.sessions-control-strip,\s*\.sessions-action-strip\s*{[^}]*border-top:\s*1px solid var\(--surface-divider-strong\);/s);
    expect(providerStyles).toMatch(/\.session-detail-empty-state\s*{[^}]*background:\s*var\(--surface-stage-subtle\);/s);
    expect(providerStyles).toMatch(/\.danger-zone\s*{[^}]*border:\s*1px solid var\(--surface-danger-panel-border\);[^}]*background:\s*var\(--surface-danger-panel-bg\);/s);
    expect(providerStyles).toMatch(/\.hotspot-card\s*{[^}]*background:\s*var\(--surface-elevated-subtle-max\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-card\s*{[^}]*background:\s*var\(--surface-elevated-subtle-alt\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-card\.is-warning\s*{[^}]*border-color:\s*var\(--state-warn-border-soft-base\);/s);
    expect(providerStyles).toMatch(/\.provider-advanced-shell\s*{[^}]*background:\s*var\(--surface-stage-subtle-strong\);/s);
    expect(providerStyles).toMatch(/\.capability-chip\s*{[^}]*background:\s*var\(--surface-elevated-subtle\);/s);
    expect(providerStyles).toMatch(/\.capability-chip\.is-on\s*{[^}]*border-color:\s*var\(--state-success-border\);[^}]*background:\s*var\(--state-success-bg-muted\);/s);
    expect(providerStyles).toMatch(/\.capability-chip\.is-off\s*{[^}]*border-color:\s*var\(--state-muted-border\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node\s*{[^}]*background:\s*var\(--surface-elevated-subtle-mid\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node\.is-done\s*{[^}]*border-color:\s*var\(--state-success-border\);[^}]*background:\s*var\(--state-success-bg-muted\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node\.is-pending\s*{[^}]*border-color:\s*var\(--state-info-border\);[^}]*background:\s*var\(--state-info-bg\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-node\.is-blocked\s*{[^}]*border-color:\s*var\(--state-warn-border\);[^}]*background:\s*var\(--state-warn-bg-balanced\);/s);
    expect(providerStyles).toMatch(/\.provider-flow-config\s*{[^}]*background:\s*var\(--surface-elevated-subtle-strong\);/s);
    expect(providerStyles).toMatch(/\.provider-slow-badge\s*{[^}]*background:\s*var\(--surface-provider-slow-badge\);/s);
    expect(providerStyles).toMatch(/\.provider-slow-row td\s*{[^}]*background:\s*var\(--surface-provider-slow-row\);/s);
    expect(providerStyles).toMatch(/\.provider-slow-row:hover td\s*{[^}]*background:\s*var\(--surface-provider-slow-row-hover\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel tbody tr\.active-row td\s*{[^}]*background:\s*var\(--surface-active-row-bg\);/s);
    expect(providerStyles).toMatch(/\.provider-roots\s*{[^}]*background:\s*var\(--surface-elevated-subtle-soft\);/s);
    expect(providerStyles).toMatch(/\.data-source-card\s*{[^}]*background:\s*var\(--surface-elevated-subtle\);/s);
    expect(providerStyles).toMatch(/\.data-source-card\.is-present\s*{[^}]*border-color:\s*var\(--state-success-border-soft-base\);/s);
    expect(providerStyles).toMatch(/\.data-source-card\.is-missing\s*{[^}]*border-color:\s*var\(--state-muted-border-soft\);/s);
    expect(providerStyles).toMatch(/\.provider-tab\.is-slow\s*{[^}]*background:\s*var\(--surface-tab-warn\);/s);
    expect(providerStyles).toMatch(/\.table-wrap\s*{[^}]*background:\s*var\(--surface-table-wrap\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel\s*{[^}]*background:\s*var\(--surface-stage-soft\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel > header\s*{[^}]*border-bottom:\s*1px solid var\(--surface-divider-muted\);[^}]*background:\s*var\(--surface-table-header\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel \.sub-toolbar\s*{[^}]*background:\s*var\(--surface-table-toolbar\);[^}]*border-bottom:\s*1px solid var\(--surface-divider-faint\);/s);
    expect(providerStyles).toMatch(/th,\s*td\s*{[^}]*border-bottom:\s*1px solid var\(--surface-divider-faint\);/s);
    expect(providerStyles).toMatch(/th\s*{[^}]*background:\s*var\(--surface-table-head\);/s);
    expect(providerStyles).toMatch(/tr:hover td\s*{[^}]*background:\s*var\(--surface-table-row-hover\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel tbody tr:nth-child\(even\) td\s*{[^}]*background:\s*var\(--surface-table-row-alt\);/s);
    expect(providerStyles).toMatch(/\.threads-table-panel tbody tr:hover td\s*{[^}]*background:\s*var\(--surface-table-row-hover-strong\);/s);
    expect(providerStyles).toMatch(/\.status-pill-button\.status-preview:hover\s*{[^}]*border-color:\s*var\(--surface-status-preview-hover-border\);/s);
  });
});
